version: '3.8' # 使用 3.8 版本的 compose 文件格式
services:
  frontend-dev: # 服务名称可以自定义
    image: frontend-dev # 使用与 docker build -t myimage . 相同的镜像
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3001:80'
    container_name: frontend-dev # 容器名称
