version: '3.8' # 使用 3.8 版本的 compose 文件格式
services:
  myservice: # 服务名称可以自定义
    image: frontend # 使用与 docker build -t myimage . 相同的镜像
    build: . # 从当前目录的 Dockerfile 构建镜像
    ports:
      - '3000:80' # 将宿主机的 3000 端口映射到容器的 3000 端口
    container_name: loudy_v3 # 容器名称
