# STAGE 1
FROM node:20-alpine AS build

WORKDIR /app
COPY package.json ./
RUN npm  install
COPY . /app
RUN npm build
# STAGE 2
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]