import React from "react";
import "@/styles/globals.css";
import StyledComponentsRegistry from "@/lib/AntdRegistry";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body>
      <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
    </body>
  </html>
);

export default RootLayout;
