export const hintList = [
  {
    id: 2,
    title: '困擾',
    list: [
      { id: 1, name: '容貌焦慮', isSelected: false },
      { id: 2, name: '睡眠不足', isSelected: false },
      { id: 3, name: '人生迷惘', isSelected: false },
      { id: 4, name: '母胎單身', isSelected: false },
      { id: 5, name: '被分手', isSelected: false },
      { id: 6, name: '直昇機父母', isSelected: false },
      { id: 7, name: '零用錢不夠', isSelected: false },
      { id: 8, name: '升學壓力', isSelected: false },
      { id: 9, name: '手機成癮', isSelected: false },
      { id: 10, name: '學長姊很兇', isSelected: false },
      { id: 11, name: '同儕壓力', isSelected: false },
      { id: 12, name: '霸淩', isSelected: false },
      { id: 13, name: '老師很煩', isSelected: false },
    ],
  },
  {
    id: 3,
    title: '興趣',
    list: [
      { id: 14, name: '聽音樂', isSelected: false },
      { id: 15, name: '嚕貓', isSelected: false },
      { id: 16, name: '打羽球', isSelected: false },
      { id: 17, name: '跳舞', isSelected: false },
      { id: 18, name: '動漫', isSelected: false },
      { id: 19, name: '韓星', isSelected: false },
      { id: 20, name: '旅遊', isSelected: false },
      { id: 21, name: '爬山', isSelected: false },
      { id: 22, name: '彈鋼琴', isSelected: false },
      { id: 23, name: '煮早餐', isSelected: false },
      { id: 24, name: '明星三缺一', isSelected: false },
      { id: 25, name: '桌遊', isSelected: false },
      { id: 26, name: '追劇', isSelected: false },
    ],
  },
  {
    id: 4,
    title: '能力',
    list: [
      { id: 27, name: '侃侃而談', isSelected: false },
      { id: 28, name: '同理心', isSelected: false },
      { id: 29, name: '創意', isSelected: false },
      { id: 30, name: '野外求生技能', isSelected: false },
      { id: 31, name: '攝影技術', isSelected: false },
      { id: 32, name: '思辨能力', isSelected: false },
      { id: 33, name: '煮飯很好吃', isSelected: false },
      { id: 34, name: '程式開發的能力', isSelected: false },
      { id: 35, name: '聆聽的能力', isSelected: false },
      { id: 36, name: '性別意識', isSelected: false },
      { id: 37, name: '情緒智商', isSelected: false },
      { id: 38, name: '自信心', isSelected: false },
      { id: 39, name: '設計美感', isSelected: false },
    ],
  },
  {
    id: 5,
    title: '夢想',
    list: [
      { id: 40, name: '人類學家', isSelected: false },
      { id: 41, name: '設計師', isSelected: false },
      { id: 42, name: '律師', isSelected: false },
      { id: 43, name: '建築師', isSelected: false },
      { id: 44, name: '機械工程師', isSelected: false },
      { id: 45, name: '農夫', isSelected: false },
      { id: 46, name: '天文學家', isSelected: false },
      { id: 47, name: '動物學家', isSelected: false },
      { id: 48, name: '能源專家', isSelected: false },
      { id: 49, name: '業務', isSelected: false },
      { id: 50, name: '專案經理', isSelected: false },
      { id: 51, name: '民意代表', isSelected: false },
      { id: 52, name: '教育工作者', isSelected: false },
    ],
  },
  {
    id: 6,
    title: '個人特質',
    list: [
      { id: 53, name: '天馬行空', isSelected: false },
      { id: 54, name: '活力充沛', isSelected: false },
      { id: 55, name: '情感細膩', isSelected: false },
      { id: 56, name: '深思熟慮', isSelected: false },
      { id: 57, name: '完美主義', isSelected: false },
      { id: 58, name: '謹慎務實', isSelected: false },
      { id: 59, name: '不喜出頭', isSelected: false },
      { id: 60, name: '決策快速', isSelected: false },
      { id: 61, name: '有話直說', isSelected: false },
      { id: 62, name: '企圖心強', isSelected: false },
      { id: 63, name: '善傾聽', isSelected: false },
      { id: 64, name: '有耐心毅力', isSelected: false },
      { id: 65, name: '以和為貴', isSelected: false },
    ],
  },
]
